### ISSUE TITLE
Enable windows job on travis

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/interop#5]
With the initial implementation merged #4 , we will need to enable windows job on travis afterwards.

`go-libp2p-daemon` has evolved to use `multiaddr` as a unix socket path, instead of the unix socket itself. In this context, for windows purposes as stated on [libp2p/go-libp2p-daemon#61](https://github.com/libp2p/go-libp2p-daemon/pull/61), we can use tcp sockets for communicating between the `daemon-client` and the `daemon`.

So, we need the following issues solved to enable the windows CI here:

- [x] [multiformats/js-multiaddr#82](https://github.com/multiformats/js-multiaddr/issues/82)
- [x] [libp2p/js-libp2p-daemon#9](https://github.com/libp2p/js-libp2p-daemon/issues/9)
- [x] [libp2p/js-libp2p-daemon-client#5](https://github.com/libp2p/js-libp2p-daemon-client/issues/5)
